const productos = [
    {
        id: '1',
        titulo:'Lechuga Francesa',
        imagen: '/static/imagenes/lechugas.jpg',
        nombre: 'Lechuga Francesa',
        precio: 50.23,
        descripcion: "Lechuga francesa hidropónica" ,
        stock: 120,
        category:"verduras",
        descripcion_extendida:' Tomates orgánicos cultivados de forma orgánica en la provincia de Mendoza',
    },
    {
        id: '2',
        imagen: '/static/imagenes/tomates.jpg',
        titulo: 'Tomate Redondo',
        precio: 50,
        descripcion: "Tomate redondo cultivado y cosechado de  forma orgánica.",
        stock: 10,
        category:"verduras",
        descripcion_extendida:' Tomates orgánicos cultivados de forma orgánica en la provincia de Mendoza',
    },
    {
        id: '3',
        imagen: '/static/imagenes/zanahorias.jpg',
        titulo: 'Zanahorias',
        precio: 50,
        descripcion: "Zanahorias envasadas en origen. Bolsa de 1 Kg.",
        stock: 10,
        category:"verduras",
        descripcion_extendida:' Tomates orgánicos cultivados de forma orgánica en la provincia de Mendoza',
    },
    {
        id: '4',
        imagen: '/static/imagenes/manzanas.jpg',
        titulo: 'Manzanas',
        precio: 50,
        descripcion: "Manzanas rojas de origen orgánico",
        stock: 10,
        category:"frutas",
        descripcion_extendida:' Tomates orgánicos cultivados de forma orgánica en la provincia de Mendoza',
    },
    {
        id: '5',
        imagen: '/static/imagenes/duraznos.jpg',
        titulo: 'Duranzos',
        precio: 50,
        descripcion: "Duraznos de origen orgánico",
        stock: 10,
        category:"frutas",
        descripcion_extendida:' Tomates orgánicos cultivados de forma orgánica en la provincia de Mendoza',
    },
    {
        id: '6',
        imagen: '/static/imagenes/ciruelas.jpg',
        titulo: 'Ciruelas',
        precio: 50,
        descripcion: "Ciruela morada de origen orgánico",
        stock: 10,
        category:"frutas",
        descripcion_extendida:' Tomates orgánicos cultivados de forma orgánica en la provincia de Mendoza',
    },
];
export default productos;